plugins:
  terminal:
    executor: central_deployment_agent
    source: https://github.com/Cloudify-PS/cloudify-terminal-plugin/archive/master.zip
    package_name: cloudify-terminal-plugin
    package_version: '0.1'

node_types:

  cloudify.terminal.raw:
    derived_from: cloudify.nodes.Root
    properties:
      terminal_auth:
        # login credentials for ios server
        default:
          user: ""
          password: ""
          ip: ""
          key_content: ""
          port: 22
          # list of prompts accepted from device
          promt_check: []
          # list of possible errors without new line
          errors: []

    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: terminal.cloudify_terminal.tasks.run
          inputs: {}
        configure:
          implementation: terminal.cloudify_terminal.tasks.run
          inputs: {}
        start:
          implementation: terminal.cloudify_terminal.tasks.run
          inputs: {}
        stop:
          implementation: terminal.cloudify_terminal.tasks.run
          inputs: {}
        delete:
          implementation: terminal.cloudify_terminal.tasks.run
          inputs: {}
